<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AcuseEmailConfigSeeder extends Seeder {
    public function run(): void {
        $configs = [
            [
                'form_type'       => 'vendedor',
                'subject'         => 'Recibimos tu solicitud de opinión de valor · Home del Valle',
                'badge'           => 'Solicitud de venta recibida',
                'titulo'          => '¡Listo {{nombre}}, comenzamos el análisis!',
                'bajada'          => 'Vamos a preparar la opinión de valor de tu {{tipo_propiedad}} en <strong style="color:#0E304B;">{{colonia}}</strong> y te contactamos en menos de 24 horas hábiles.',
                'nota'            => 'Sin compromiso y sin costos. Solo cobramos comisión al cerrar exitosamente.',
                'cta1_label'      => 'Ver precio por m² en {{colonia}}',
                'cta1_type'       => 'precios_colonia',
                'cta1_url_static' => 'https://homedelvalle.mx/precios',
                'cta2_label'      => 'Ver propiedades similares',
                'cta2_type'       => 'propiedades_compra',
                'cta2_url_static' => 'https://homedelvalle.mx/propiedades',
                'paso1_icon'      => 'icon-home.png',
                'paso1_titulo'    => 'Analizamos tu propiedad',
                'paso1_desc'      => 'Revisamos ubicación, metraje y comparables del mercado actual en Benito Juárez.',
                'paso2_icon'      => 'icon-chart.png',
                'paso2_titulo'    => 'Te enviamos la opinión de valor',
                'paso2_desc'      => 'Precio competitivo basado en datos reales, no estimados genéricos.',
                'paso3_icon'      => 'icon-shield.png',
                'paso3_titulo'    => 'Diseñamos tu estrategia',
                'paso3_desc'      => 'Fotografía profesional, marketing digital y red de compradores calificados.',
            ],
            [
                'form_type'       => 'comprador',
                'subject'         => 'Recibimos tu búsqueda · Home del Valle',
                'badge'           => 'Búsqueda recibida',
                'titulo'          => '¡Estamos curándolo{{nombre}}!',
                'bajada'          => 'Buscaremos <strong style="color:#0E304B;">{{tipo_inmueble}}</strong> en <strong style="color:#0E304B;">{{zonas}}</strong> dentro de tu presupuesto. Máximo 72h hábiles, 3–5 opciones, no catálogos.',
                'nota'            => 'Gratuito para el comprador. La comisión la cubre el vendedor al cierre.',
                'cta1_label'      => 'Ver propiedades disponibles',
                'cta1_type'       => 'propiedades_compra',
                'cta1_url_static' => 'https://homedelvalle.mx/propiedades',
                'cta2_label'      => 'Observatorio de precios',
                'cta2_type'       => 'precios',
                'cta2_url_static' => 'https://homedelvalle.mx/precios',
                'paso1_icon'      => 'icon-pin.png',
                'paso1_titulo'    => 'Filtramos el mercado',
                'paso1_desc'      => 'Revisamos inventario propio, red de contactos privada y mercado abierto.',
                'paso2_icon'      => 'icon-check.png',
                'paso2_titulo'    => 'Selección curada',
                'paso2_desc'      => 'Solo te enviamos 3–5 opciones que realmente coinciden con tu brief.',
                'paso3_icon'      => 'icon-shield.png',
                'paso3_titulo'    => 'Acompañamiento al cierre',
                'paso3_desc'      => 'Negociación, due diligence legal y firma de escrituras incluidos.',
            ],
            [
                'form_type'       => 'arrendatario',
                'subject'         => 'Recibimos tu búsqueda de renta · Home del Valle',
                'badge'           => 'Búsqueda de renta recibida',
                'titulo'          => '¡Recibimos tu búsqueda{{nombre}}!',
                'bajada'          => 'Curaremos opciones de renta en <strong style="color:#0E304B;">{{zonas}}</strong> dentro de tu presupuesto. {{mascotas_texto}}',
                'nota'            => 'Gratuito para el inquilino. La comisión la cubre el propietario al cierre.',
                'cta1_label'      => 'Ver inmuebles en renta',
                'cta1_type'       => 'propiedades_renta',
                'cta1_url_static' => 'https://homedelvalle.mx/propiedades',
                'cta2_label'      => 'Observatorio de precios',
                'cta2_type'       => 'precios',
                'cta2_url_static' => 'https://homedelvalle.mx/precios',
                'paso1_icon'      => 'icon-pin.png',
                'paso1_titulo'    => 'Filtramos el inventario',
                'paso1_desc'      => 'Revisamos inmuebles propios y red privada que coincidan con tu zona, presupuesto y preferencias.',
                'paso2_icon'      => 'icon-check.png',
                'paso2_titulo'    => 'Selección curada',
                'paso2_desc'      => 'Solo te enviamos 3–5 opciones que realmente cumplen tu brief. Sin catálogos masivos.',
                'paso3_icon'      => 'icon-homestep.png',
                'paso3_titulo'    => 'Te acompañamos a firmar',
                'paso3_desc'      => 'Revisamos contrato y póliza jurídica contigo antes de firmar. Sin cláusulas escondidas.',
            ],
            [
                'form_type'       => 'propietario_renta',
                'subject'         => 'Recibimos tu solicitud para rentar · Home del Valle',
                'badge'           => 'Solicitud para rentar recibida',
                'titulo'          => '¡Recibimos tu solicitud{{nombre}}!',
                'bajada'          => 'Analizaremos el mercado de renta para tu <strong style="color:#0E304B;">{{tipo_propiedad}}</strong> en <strong style="color:#0E304B;">{{colonia}}</strong> y te contactamos en menos de 24h con un rango orientativo.',
                'nota'            => 'Sin costo por adelantado. Comisión solo al firmar contrato. Sin exclusividad obligatoria.',
                'cta1_label'      => 'Ver precios de renta en {{colonia}}',
                'cta1_type'       => 'precios_colonia_renta',
                'cta1_url_static' => 'https://homedelvalle.mx/precios',
                'cta2_label'      => null,
                'cta2_type'       => null,
                'cta2_url_static' => null,
                'paso1_icon'      => 'icon-pin.png',
                'paso1_titulo'    => 'Analizamos el mercado',
                'paso1_desc'      => 'Revisamos ubicación, características y comparables de renta en tu colonia.',
                'paso2_icon'      => 'icon-chart.png',
                'paso2_titulo'    => 'Te enviamos el rango de renta',
                'paso2_desc'      => 'Precio competitivo basado en datos reales del mercado. Sin inflar para captar la firma.',
                'paso3_icon'      => 'icon-shield.png',
                'paso3_titulo'    => 'Diseñamos tu plan',
                'paso3_desc'      => 'Calificación de inquilinos, póliza jurídica y administración integral. Tú eliges.',
            ],
            [
                'form_type'       => 'b2b',
                'subject'         => 'Recibimos tu brief calificador · Home del Valle',
                'badge'           => 'Brief recibido — Confidencial',
                'titulo'          => 'Recibimos tu brief{{nombre}}.',
                'bajada'          => 'Dirección general te contactará en <strong style="color:#0E304B;">menos de 48 horas hábiles</strong> para la llamada de calificación. Tu información es estrictamente confidencial.',
                'nota'            => 'Información tratada bajo confidencialidad. Nunca compartimos tu brief sin autorización expresa.',
                'cta1_label'      => 'Observatorio de mercado',
                'cta1_type'       => 'precios',
                'cta1_url_static' => 'https://homedelvalle.mx/precios',
                'cta2_label'      => null,
                'cta2_type'       => null,
                'cta2_url_static' => null,
                'paso1_icon'      => 'icon-check.png',
                'paso1_titulo'    => 'Calificamos tu brief',
                'paso1_desc'      => 'Revisamos objetivos, presupuesto y horizonte de inversión.',
                'paso2_icon'      => 'icon-chat.png',
                'paso2_titulo'    => 'Llamada de alineación',
                'paso2_desc'      => 'Definimos criterios técnicos y financieros con dirección general.',
                'paso3_icon'      => 'icon-pin.png',
                'paso3_titulo'    => 'Captación dirigida',
                'paso3_desc'      => 'Activamos la red para identificar activos que cumplan al 100%.',
            ],
            [
                'form_type'       => 'contacto',
                'subject'         => 'Recibimos tu mensaje · Home del Valle',
                'badge'           => 'Mensaje recibido',
                'titulo'          => '¡Recibimos tu mensaje{{nombre}}!',
                'bajada'          => 'Un asesor de <strong style="color:#0E304B;">Home del Valle</strong> te responderá en <strong style="color:#0E304B;">menos de 24 horas hábiles</strong>. Sin compromiso y sin spam.',
                'nota'            => 'Pocos inmuebles. Más control. Mejores resultados.',
                'cta1_label'      => 'Ver propiedades',
                'cta1_type'       => 'propiedades_compra',
                'cta1_url_static' => 'https://homedelvalle.mx/propiedades',
                'cta2_label'      => 'Precios por m²',
                'cta2_type'       => 'precios',
                'cta2_url_static' => 'https://homedelvalle.mx/precios',
                'paso1_icon'      => 'icon-mail.png',
                'paso1_titulo'    => 'Revisamos tu mensaje',
                'paso1_desc'      => 'Un asesor lee tu solicitud y prepara la mejor respuesta.',
                'paso2_icon'      => 'icon-chat.png',
                'paso2_titulo'    => 'Te contactamos',
                'paso2_desc'      => 'Por teléfono, email o WhatsApp según tu preferencia.',
                'paso3_icon'      => 'icon-homestep.png',
                'paso3_titulo'    => 'Asesoría personalizada',
                'paso3_desc'      => 'Sin compromiso. Solo soluciones reales para tu caso.',
            ],
        ];

        foreach ($configs as $config) {
            DB::table('acuse_email_configs')->updateOrInsert(
                ['form_type' => $config['form_type']],
                array_merge($config, ['created_at' => now(), 'updated_at' => now()])
            );
        }
    }
}
